nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: [ ]
    allow_headers: [ ]
    allow_methods: [ ]
    expose_headers: [ ]
    max_age: 0
    hosts: [ ]
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    '^/v1/':
      allow_origin: [ '*' ]
      allow_headers: [ 'X-Custom-Auth','Content-Type', 'Authorization','Cache-Control','Access-Control', 'X-Requested-With' ]
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      max_age: 3600
    '^/service/v1/':
      allow_origin: [ '*' ]
      allow_headers: [ 'X-Custom-Auth','Content-Type', 'Authorization','Cache-Control','Access-Control', 'X-Requested-With' ]
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      max_age: 3600
