security:
    encoders:
        App\Entity\Account:
            algorithm: auto
    providers:
        app_account_provider:
            entity:
                class: App\Provider\AccountUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: app_account_provider
            pattern: '^/service/v1/'
            security: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticatorSecurity       
    access_control:
        - { path: ^/service/v1/oauth2, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/service/v1/oauth2, methods: [GET, DELETE], roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/service/v1/book, methods: [POST, PUT, DELETE], roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/service/v1/publisher, methods: [POST, PUT, DELETE], roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/service/v1/, roles: IS_AUTHENTICATED_FULLY }
