App\Entity\Account:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      type: integer
      groups: [ 'List' ]
    name:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    email:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    scope:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    password:
      expose: true
      type: string
    plainPassword:
      expose: true
      type: string
      groups: [ 'Create' ]
    type:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    enabled:
      expose: true
      type: boolean
      groups: [ 'Show', 'List' ]
    createdAt:
      expose: true
      type: datetimeinterface
      groups: [ 'Show', 'List', 'Create' ]
    modifiedAt:
      expose: true
      type: datetimeinterface
      groups: [ 'Show', 'List', 'Create' ]
