App\Entity\Book:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      type: integer
      groups: [ 'List' ]
    title:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    author:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    quantityPages:
      expose: true
      type: integer
      groups: [ 'Show', 'List', 'Create' ]
    releaseDate:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
    publisher:
      expose: true
      type: App\Entity\Publisher
      groups: [ 'Show', 'List', 'Create' ]
