App\Entity\Publisher:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      type: integer
      groups: [ 'List' ]
    name:
      expose: true
      type: string
      groups: [ 'Show', 'List', 'Create' ]
