App\Model\OAuth2Request:
  exclusion_policy: ALL
  properties:
    username:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
    password:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
    grantType:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
