App\Model\OAuth2Response:
  exclusion_policy: All
  properties:
    accessToken:
      expose: true
      type: string
      group: [ "Show", "Create" ]
    address:
      expose: true
      type: string
      group: [ "Show", "Create" ]
    expiresIn:
      expose: true
      type: integer
      group: [ "Show", "Create" ]
    tokenType:
      expose: true
      type: string
      group: [ "Show", "Create" ]
    scope:
      expose: true
      type: string
      group: [ "Show", "Create" ]
    refreshToken:
      expose: true
      type: string
      group: [ "Show", "Create" ]