App\Model\OAuth2Response:
  exclusion_policy: ALL
  properties:
    accessToken:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
    address:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
    expiresIn:
      expose: true
      type: integer
      groups: [ 'Show', 'Create' ]
    tokenType:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
    scope:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]
    refreshToken:
      expose: true
      type: string
      groups: [ 'Show', 'Create' ]