account_list:
  path: /service/v1/account
  controller: App\Controller\AccountController::listAction
  methods: GET

account_show:
  path: /service/v1/account/{id}
  controller: App\Controller\AccountController::showAction
  methods: GET
  requirements:
    id: '\d+'

account_create:
  path: /service/v1/account
  controller: App\Controller\AccountController::createAction
  methods: POST

account_update:
  path: /service/v1/account/{id}
  controller: App\Controller\AccountController::updateAction
  methods: UPDATE
  requirements:
    id: '\d+'

account_delete:
  path: /service/v1/account/{id}
  controller: App\Controller\AccountController::deleteAction
  methods: DELETE
  requirements:
    id: '\d+'
