book_list:
  path: /service/v1/book
  controller: App\Controller\BookController::listAction
  methods: GET

book_show:
  path: /service/v1/book/{id}
  controller: App\Controller\BookController::showAction
  methods: GET
  requirements:
    id: '\d+'

book_create:
  path: /service/v1/book
  controller: App\Controller\BookController::createAction
  methods: POST

book_update:
  path: /service/v1/book/{id}
  controller: App\Controller\BookController::updateAction
  methods: UPDATE
  requirements:
    id: '\d+'

book_delete:
  path: /service/v1/book/{id}
  controller: App\Controller\BookController::deleteAction
  methods: DELETE
  requirements:
    id: '\d+'
