publisher_list:
  path:       /service/v1/publisher
  controller: App\Controller\PublisherController::listAction
  methods:    GET

publisher_show:
  path:         /service/v1/publisher/{id}
  controller:   App\Controller\PublisherController::showAction
  methods:      GET
  requirements:
    '\d+'

publisher_create:
  path:       /service/v1/publisher
  controller: App\Controller\PublisherController::createAction
  methods:    POST